### ISSUE TITLE
verification is not working

### ISSUE THREAD

**Issue by h7ndrxx** [WildSiphon/Mailfoguess#3]
The verification is not working; it consistently returns 'false' even when tested with real emails

**Comment by WildSiphon** [comment]
On what domains did you get false results ?

After further investigation, the verification for *gmail* and *yahoo* can lead to a "false false" (don't know how to say it) due to a rate limit.

I can't fix that because I rely on [holehe](https://github.com/megadose/holehe) for the verification part.

I will display a warning but can't do more.
